### PR TITLE
Fixes Issue 3

### PR DESCRIPTION
**Pull request by Hood-fr**
Static comment block

### CODE REVIEW

**Comment by mistic100** [comment]
I don't remember what exactly this code is supposed to do but it's certainly here for a reason.

I don't reproduce the bug you mention with 300 thumbnails so I need a little more info.

**Comment by Hood-fr** [comment]
OK, on my side it is systematic. Using PWG 2.9.4 with Stripped theme, but also appears with Elegant. 
Screenshot 1 shows the issues on an album with 168 photos, 80 photos /page. Issue appears on the first two pages, but not on the third one (only 8 photos). See from screenshot how the attributes of element.style switches for static to absolute. Everything is fine when position is static, but goes hectic when it is absolute. Hence my mod
capture4
capture3
capture2
capture1

**Comment by mistic100** [comment]
Looks like the problem is specific with gdThumb. No problem with the standard layout nor with GThumb+

**Comment by Hood-fr** [comment]
OK, I'll have a look at it. Still is there a reason why this block should have an absolute position in the frame? In other words, with GDThumb+ or standard layout, does the position attribute ever switch to absolute ?

**Comment by Hood-fr** [comment]
OK, I confirm the following : I have the issue when gbThumb is displaying more than 17 rows of pictures, (each row 200px, separated by 10px, so 3560px total). Below that no issue

**Pull request closed without merging**
